server.port: ${APP_PORT}

spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        "[format_sql]": true
        "[show_sql]": false

logging:
  level:
    root: INFO
    "[com.inssider]": INFO
    "[org.springframework.web]": WARN
    "[org.springframework.security]": ERROR
    "[org.hibernate]": WARN

management.endpoints.web.exposure.include: health
