# https://docs.spring.io/spring-boot/appendix/application-properties

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Asia/Seoul
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${APP_EMAIL}
    password: ${APP_EMAIL_PASSWORD}
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.connectiontimeout]": 10000
      "[mail.smtp.timeout]": 10000
      "[mail.smtp.writetimeout]": 10000

spring.jpa:
  open-in-view: false
  hibernate:
    ddl-auto: none
    naming.physical-strategy: com.inssider.api.common.config.PluralSnakeCaseNamingStrategy

# https://springdoc.org/properties.html#_swagger_ui_properties
springdoc:
  swagger-ui:
    use-root-path: true
    display-request-duration: true
  paths-to-match:
    - /api/**
