server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: user
    password: user
  mail:
    username: inssider.api@gmail.com
    password: oquecufsaxeufnav # https://myaccount.google.com/u/3/apppasswords

spring.jpa.hibernate.ddl-auto: create-drop

management.endpoints.web.exposure.include: "*"

spring.output.ansi.enabled: always
logging.level:
  "[com.inssider]": debug
  "[org.springframework.security]": debug
  "[org.springframework.boot.autoconfigure]": warn
