name: Publish Docker image on Semver tag push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Semver tag to release (ex v1.0.0)"
        required: true
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.event.ref == 'refs/heads/main')
    env:
      DOCKER_BUILD_RECORD_RETENTION_DAYS: 1
      RELEASE_TAG: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.ORGANIZATION_NAME }}-${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{major}},value=${{ env.RELEASE_TAG }}
            type=semver,pattern={{major}}.{{minor}},value=${{ env.RELEASE_TAG }}
            type=semver,pattern={{version}},value=${{ env.RELEASE_TAG }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3.10.0
        
      - name: Build and push
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags || 'latest' }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save Docker tag for deployment
        run: |
          echo "${{ steps.meta.outputs.tags }}" | head -n1 > docker_tag.txt

      - name: Upload Docker metadata
        uses: actions/upload-artifact@v4
        with:
          name: docker-metadata
          path: docker_tag.txt
          retention-days: 1